apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-db
  template:
    metadata:
      labels:
        app: mssql-db
    spec:
      containers:
        - name: mssql-db
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "YourStrong!Password"
            - name: MSSQL_PID
              value: "Express"
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-db-service
spec:
  selector:
    app: mssql-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
